package project_ferretech;

import project_ferretech.daos.DetalleVentasDAO;
import project_ferretech.daos.CompraDAO;
import project_ferretech.daos.ClienteDAO;
import project_ferretech.daos.EmpleadoDAO;
import project_ferretech.daos.VentaDAO;
import project_ferretech.daos.ProductoDAO;
import project_ferretech.daos.ProveedorDAO;
import project_ferretech.daos.CategoriaDAO;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

public class Menu extends javax.swing.JFrame {
    
    public Menu() {
        initComponents();
        
    }

    // Método para obtener un nuevo ID
    private int obtenerNuevoID() {
        int nuevoID = 1;
        try (Connection con = ConexionOracle.getConnection(); Statement stmt = con.createStatement(); ResultSet rs = stmt.executeQuery("SELECT NVL(MAX(ID_CATEGORIA), 0) + 1 FROM CATEGORIAS")) {
            if (rs.next()) {
                nuevoID = rs.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return nuevoID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Empleados = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        CrearEmpleado = new javax.swing.JButton();
        EditarEmpleado = new javax.swing.JButton();
        EliminarEmpleado = new javax.swing.JButton();
        Clientes = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        CrearClientes = new javax.swing.JButton();
        EditarClientes = new javax.swing.JButton();
        EliminarClientes = new javax.swing.JButton();
        Compras = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        CrearCompra = new javax.swing.JButton();
        EditarCompra = new javax.swing.JButton();
        EliminarCompra = new javax.swing.JButton();
        Ventas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        CrearVentas = new javax.swing.JButton();
        EditarVentas = new javax.swing.JButton();
        BorrarVentas = new javax.swing.JButton();
        Categorias = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCategorias = new javax.swing.JTable();
        CrearCategoria = new javax.swing.JButton();
        EditarCategoria = new javax.swing.JButton();
        BorrarCategoria = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaProveedor = new javax.swing.JTable();
        CrearProveedor = new javax.swing.JButton();
        EditarProveedor = new javax.swing.JButton();
        BorrarProveedor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        CrearProducto = new javax.swing.JButton();
        EditarProducto = new javax.swing.JButton();
        BorrarProducto = new javax.swing.JButton();
        DetVentas = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablaDetVentas = new javax.swing.JTable();
        CrearDetVentas = new javax.swing.JButton();
        EditarDetVentas = new javax.swing.JButton();
        EliminarDetVentas = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FERRETEC");
        setForeground(new java.awt.Color(204, 255, 204));
        setName(""); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 102));
        jTabbedPane1.setFont(new java.awt.Font("STIXGeneral", 0, 15)); // NOI18N
        jTabbedPane1.setName("FERRETECH"); // NOI18N

        tablaEmpleados.setModel(project_ferretech.daos.EmpleadoDAO.obtenerEmpleados());
        tablaEmpleados.setName("FERRETECH"); // NOI18N
        jScrollPane3.setViewportView(tablaEmpleados);

        CrearEmpleado.setText("Crear");
        CrearEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEmpleadoActionPerformed(evt);
            }
        });

        EditarEmpleado.setText("Editar");
        EditarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEmpleadoActionPerformed(evt);
            }
        });

        EliminarEmpleado.setText("Eliminar");
        EliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmpleadosLayout = new javax.swing.GroupLayout(Empleados);
        Empleados.setLayout(EmpleadosLayout);
        EmpleadosLayout.setHorizontalGroup(
            EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditarEmpleado)
                    .addComponent(EliminarEmpleado)
                    .addComponent(CrearEmpleado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmpleadosLayout.setVerticalGroup(
            EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(EmpleadosLayout.createSequentialGroup()
                        .addComponent(CrearEmpleado)
                        .addGap(18, 18, 18)
                        .addComponent(EditarEmpleado)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarEmpleado)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Empleados", Empleados);

        tablaClientes.setModel(project_ferretech.daos.ClienteDAO.obtenerClientes());
        tablaClientes.setName("FERRETECH"); // NOI18N
        jScrollPane5.setViewportView(tablaClientes);

        CrearClientes.setText("Crear");
        CrearClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearClientesActionPerformed(evt);
            }
        });

        EditarClientes.setText("Editar");
        EditarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarClientesActionPerformed(evt);
            }
        });

        EliminarClientes.setText("Eliminar");
        EliminarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClientesLayout = new javax.swing.GroupLayout(Clientes);
        Clientes.setLayout(ClientesLayout);
        ClientesLayout.setHorizontalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditarClientes)
                    .addComponent(EliminarClientes)
                    .addComponent(CrearClientes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ClientesLayout.setVerticalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(ClientesLayout.createSequentialGroup()
                        .addComponent(CrearClientes)
                        .addGap(18, 18, 18)
                        .addComponent(EditarClientes)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarClientes)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clientes", Clientes);

        tablaCompras.setModel(project_ferretech.daos.CompraDAO.obtenerCompras());
        jScrollPane2.setViewportView(tablaCompras);

        CrearCompra.setText("Crear");
        CrearCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCompraActionPerformed(evt);
            }
        });

        EditarCompra.setText("Editar");
        EditarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarCompraActionPerformed(evt);
            }
        });

        EliminarCompra.setText("Eliminar");
        EliminarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ComprasLayout = new javax.swing.GroupLayout(Compras);
        Compras.setLayout(ComprasLayout);
        ComprasLayout.setHorizontalGroup(
            ComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(ComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditarCompra)
                    .addComponent(EliminarCompra)
                    .addComponent(CrearCompra))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ComprasLayout.setVerticalGroup(
            ComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(ComprasLayout.createSequentialGroup()
                        .addComponent(CrearCompra)
                        .addGap(18, 18, 18)
                        .addComponent(EditarCompra)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarCompra)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Compras", Compras);

        tablaVentas.setModel(project_ferretech.daos.VentaDAO.obtenerVentas());
        jScrollPane4.setViewportView(tablaVentas);

        CrearVentas.setText("Crear");
        CrearVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearVentasActionPerformed(evt);
            }
        });

        EditarVentas.setText("Editar");
        EditarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarVentasActionPerformed(evt);
            }
        });

        BorrarVentas.setText("Eliminar");
        BorrarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VentasLayout = new javax.swing.GroupLayout(Ventas);
        Ventas.setLayout(VentasLayout);
        VentasLayout.setHorizontalGroup(
            VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BorrarVentas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VentasLayout.createSequentialGroup()
                        .addGroup(VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CrearVentas)
                            .addComponent(EditarVentas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        VentasLayout.setVerticalGroup(
            VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(VentasLayout.createSequentialGroup()
                        .addComponent(CrearVentas)
                        .addGap(18, 18, 18)
                        .addComponent(EditarVentas)
                        .addGap(18, 18, 18)
                        .addComponent(BorrarVentas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ventas", Ventas);

        tablaCategorias.setModel(CategoriaDAO.obtenerCategorias());
        jScrollPane1.setViewportView(tablaCategorias);

        CrearCategoria.setText("Crear");
        CrearCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCategoriaActionPerformed(evt);
            }
        });

        EditarCategoria.setText("Editar");
        EditarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarCategoriaActionPerformed(evt);
            }
        });

        BorrarCategoria.setText("Eliminar");
        BorrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CategoriasLayout = new javax.swing.GroupLayout(Categorias);
        Categorias.setLayout(CategoriasLayout);
        CategoriasLayout.setHorizontalGroup(
            CategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BorrarCategoria, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CategoriasLayout.createSequentialGroup()
                        .addGroup(CategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CrearCategoria)
                            .addComponent(EditarCategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        CategoriasLayout.setVerticalGroup(
            CategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(CategoriasLayout.createSequentialGroup()
                        .addComponent(CrearCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(EditarCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(BorrarCategoria)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Categorias", Categorias);

        tablaProveedor.setModel(ProveedorDAO.obtenerProveedores());
        jScrollPane6.setViewportView(tablaProveedor);

        CrearProveedor.setText("Crear");
        CrearProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearProveedorActionPerformed(evt);
            }
        });

        EditarProveedor.setText("Editar");
        EditarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarProveedorActionPerformed(evt);
            }
        });

        BorrarProveedor.setText("Eliminar");
        BorrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BorrarProveedor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CrearProveedor)
                            .addComponent(EditarProveedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CrearProveedor)
                        .addGap(18, 18, 18)
                        .addComponent(EditarProveedor)
                        .addGap(18, 18, 18)
                        .addComponent(BorrarProveedor)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Proveedores", jPanel1);

        tablaProducto.setModel(ProductoDAO.obtenerProductos());
        jScrollPane7.setViewportView(tablaProducto);

        CrearProducto.setText("Crear");
        CrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearProductoActionPerformed(evt);
            }
        });

        EditarProducto.setText("Editar");
        EditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarProductoActionPerformed(evt);
            }
        });

        BorrarProducto.setText("Eliminar");
        BorrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BorrarProducto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CrearProducto)
                            .addComponent(EditarProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CrearProducto)
                        .addGap(18, 18, 18)
                        .addComponent(EditarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(BorrarProducto)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Productos", jPanel2);

        tablaDetVentas.setModel(project_ferretech.daos.DetalleVentasDAO.obtenerDetalleVentas());
        tablaDetVentas.setName("FERRETECH"); // NOI18N
        jScrollPane8.setViewportView(tablaDetVentas);

        CrearDetVentas.setText("Crear");
        CrearDetVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearDetVentasActionPerformed(evt);
            }
        });

        EditarDetVentas.setText("Editar");
        EditarDetVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarDetVentasActionPerformed(evt);
            }
        });

        EliminarDetVentas.setText("Eliminar");
        EliminarDetVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarDetVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DetVentasLayout = new javax.swing.GroupLayout(DetVentas);
        DetVentas.setLayout(DetVentasLayout);
        DetVentasLayout.setHorizontalGroup(
            DetVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(DetVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditarDetVentas)
                    .addComponent(EliminarDetVentas)
                    .addComponent(CrearDetVentas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DetVentasLayout.setVerticalGroup(
            DetVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DetVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(DetVentasLayout.createSequentialGroup()
                        .addComponent(CrearDetVentas)
                        .addGap(18, 18, 18)
                        .addComponent(EditarDetVentas)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarDetVentas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Detalle Ventas", DetVentas);

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("STIXGeneral", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("FerreTech");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(206, 206, 206))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BorrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarCategoriaActionPerformed
        CategoriaDAO.eliminarCategoriaDesdeTabla(tablaCategorias, this);
    }//GEN-LAST:event_BorrarCategoriaActionPerformed

    private void EditarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarCategoriaActionPerformed
        CategoriaDAO.actualizarCategoriaDesdeTabla(tablaCategorias, this);
    }//GEN-LAST:event_EditarCategoriaActionPerformed

    private void CrearCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCategoriaActionPerformed
        CategoriaDAO.crearCategoriaDesdeInput(tablaCategorias, this);
    }//GEN-LAST:event_CrearCategoriaActionPerformed

    private void CrearCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCompraActionPerformed
        CompraDAO.crearCompra(this, tablaCompras);
    }//GEN-LAST:event_CrearCompraActionPerformed

    private void EditarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarCompraActionPerformed
        CompraDAO.editarCompra(this, tablaCompras);
    }//GEN-LAST:event_EditarCompraActionPerformed

    private void EliminarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCompraActionPerformed
        CompraDAO.eliminarCompra(this, tablaCompras);
    }//GEN-LAST:event_EliminarCompraActionPerformed

    private void EliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEmpleadoActionPerformed
        EmpleadoDAO.eliminarEmpleado(this, tablaEmpleados);
    }//GEN-LAST:event_EliminarEmpleadoActionPerformed

    private void EditarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarClientesActionPerformed
        ClienteDAO.editarCliente(this, tablaClientes);
    }//GEN-LAST:event_EditarClientesActionPerformed

    private void EliminarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarClientesActionPerformed
        ClienteDAO.eliminarCliente(this, tablaClientes);
    }//GEN-LAST:event_EliminarClientesActionPerformed

    private void CrearVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearVentasActionPerformed
        VentaDAO.crearVentaDesdeFormulario(tablaVentas, this);
    }//GEN-LAST:event_CrearVentasActionPerformed

    private void EditarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarVentasActionPerformed
        VentaDAO.actualizarVentaDesdeFormulario(tablaVentas, this);
    }//GEN-LAST:event_EditarVentasActionPerformed

    private void BorrarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarVentasActionPerformed
        VentaDAO.eliminarVentaDesdeTabla(tablaVentas, this);
    }//GEN-LAST:event_BorrarVentasActionPerformed

    private void CrearProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearProveedorActionPerformed
        ProveedorDAO.crearProveedorDesdeFormulario(tablaProveedor, this);
    }//GEN-LAST:event_CrearProveedorActionPerformed

    private void EditarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarProveedorActionPerformed
        ProveedorDAO.actualizarProveedorDesdeTabla(tablaProveedor, this);
    }//GEN-LAST:event_EditarProveedorActionPerformed

    private void BorrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarProveedorActionPerformed
        ProveedorDAO.eliminarProveedorDesdeTabla(tablaProveedor, this);
    }//GEN-LAST:event_BorrarProveedorActionPerformed

    private void CrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearProductoActionPerformed
        
        ProductoDAO.insertarProductoDesdeFormulario(tablaProducto, this);
    }//GEN-LAST:event_CrearProductoActionPerformed

    private void EditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarProductoActionPerformed
        
        ProductoDAO.actualizarProductoDesdeTabla(tablaProducto, this);
    }//GEN-LAST:event_EditarProductoActionPerformed

    private void BorrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarProductoActionPerformed
        
        ProductoDAO.eliminarProductoDesdeTabla(tablaProducto, this);        
    }//GEN-LAST:event_BorrarProductoActionPerformed

    private void CrearDetVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearDetVentasActionPerformed
        DetalleVentasDAO.crearDetalleVenta(this, tablaDetVentas);
    }//GEN-LAST:event_CrearDetVentasActionPerformed

    private void EditarDetVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarDetVentasActionPerformed
        DetalleVentasDAO.editarDetalleVenta(this, tablaDetVentas);
    }//GEN-LAST:event_EditarDetVentasActionPerformed

    private void EliminarDetVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarDetVentasActionPerformed
        DetalleVentasDAO.eliminarDetalleVenta(this, tablaDetVentas);
    }//GEN-LAST:event_EliminarDetVentasActionPerformed

    private void EditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEmpleadoActionPerformed
        EmpleadoDAO.editarEmpleado(this, tablaEmpleados);
    }//GEN-LAST:event_EditarEmpleadoActionPerformed

    private void CrearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEmpleadoActionPerformed
        EmpleadoDAO.crearEmpleado(this, tablaEmpleados);
    }//GEN-LAST:event_CrearEmpleadoActionPerformed

    private void CrearClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearClientesActionPerformed
        ClienteDAO.crearCliente(this, tablaClientes);
    }//GEN-LAST:event_CrearClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarCategoria;
    private javax.swing.JButton BorrarProducto;
    private javax.swing.JButton BorrarProveedor;
    private javax.swing.JButton BorrarVentas;
    private javax.swing.JPanel Categorias;
    private javax.swing.JPanel Clientes;
    private javax.swing.JPanel Compras;
    private javax.swing.JButton CrearCategoria;
    private javax.swing.JButton CrearClientes;
    private javax.swing.JButton CrearCompra;
    private javax.swing.JButton CrearDetVentas;
    private javax.swing.JButton CrearEmpleado;
    private javax.swing.JButton CrearProducto;
    private javax.swing.JButton CrearProveedor;
    private javax.swing.JButton CrearVentas;
    private javax.swing.JPanel DetVentas;
    private javax.swing.JButton EditarCategoria;
    private javax.swing.JButton EditarClientes;
    private javax.swing.JButton EditarCompra;
    private javax.swing.JButton EditarDetVentas;
    private javax.swing.JButton EditarEmpleado;
    private javax.swing.JButton EditarProducto;
    private javax.swing.JButton EditarProveedor;
    private javax.swing.JButton EditarVentas;
    private javax.swing.JButton EliminarClientes;
    private javax.swing.JButton EliminarCompra;
    private javax.swing.JButton EliminarDetVentas;
    private javax.swing.JButton EliminarEmpleado;
    private javax.swing.JPanel Empleados;
    private javax.swing.JPanel Ventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaCategorias;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JTable tablaDetVentas;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTable tablaProveedor;
    private javax.swing.JTable tablaVentas;
    // End of variables declaration//GEN-END:variables
}
